### ISSUE TITLE
java.lang.NoClassDefFoundError: sun/reflect/ConstantPool with Java 9

### ISSUE THREAD

**Issue by szpak** [jhalterman/typetools#34]
We [would like](https://github.com/mockito/mockito/pull/859) to use typetools in Mockito to determine lambda's return type. It works fine with Java 8, but our Java 8+ distribution is planned to be Java 9 compatible. Unfortunately typetools seems to not work with Java 9:

```
java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
```

Do you plan to make typetools Java 9 compatible?

Full stracktrace:
```
org.mockito.internal.matchers.AssertionMatcherTest > shouldAllowToUseAssertionInLambda FAILED
    java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
        at net.jodah.typetools.TypeResolver.populateLambdaArgs(TypeResolver.java:379)
        at net.jodah.typetools.TypeResolver.getTypeVariableMap(TypeResolver.java:246)
        at net.jodah.typetools.TypeResolver.resolveRawClass(TypeResolver.java:228)
        at net.jodah.typetools.TypeResolver.resolveRawArguments(TypeResolver.java:165)
        at net.jodah.typetools.TypeResolver.resolveRawArguments(TypeResolver.java:125)
        at org.mockito.internal.util.Primitives.defaultValueForConsumerLambda(Primitives.java:74)
        at org.mockito.AdditionalMatchers.assertArg(AdditionalMatchers.java:1078)
        at org.mockito.internal.matchers.AssertionMatcherTest.shouldAllowToUseAssertionInLambda(AssertionMatcherTest.java:48)
        Caused by:
        java.lang.ClassNotFoundException: sun.reflect.ConstantPool
            at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-ea/BuiltinClassLoader.java:366)
            at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-ea/ClassLoaders.java:185)
            at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
            ... 8 more
```

A corresponding Travis [build](https://travis-ci.org/mockito/mockito/jobs/187813136#L322-L338).

**Comment by jhalterman** [comment]
Hi @szpak - 

TypeTools uses ConstantPool to resolve lambda type args in Java 8, which I understand is being removed in Java 9 - though I'm not sure how definite that is. The only other approach I'm aware of for resolving lambda type args is to inspect the bytecode using something like ASM. The problem is that lambda class definitions are generated at runtime, so there's no classfile to inspect as is typical with ASM. From what I understand, we can use a Java agent to inspect the lambda's bytecode after it's generated, but requiring a Java agent is a pretty big limitation.

I believe that @raphw has written a bit about this and perhaps can weigh in a bit more. @raphw - Any pointers on this?

**Comment by raphw** [comment]
This hack that I introduced to get hold of that bytecode is no longer working in Java 9, the instrumentation API is no longer allowed to access any type that is loaded by an anonymous class loader. The only way of doing this would be to instrument the `LambdaMetafactory` which I would not recommend. One way to do this would be to get hold of the original invokedynamic call site as the `MethodType` is stored in the call site as an argument to the lambda metafactory.

Otherwise, I am afraid, there is no good way.

**Comment by jhalterman** [comment]
@raphw Would obtaining the invokedynamic call site still require use of an agent?

**Comment by raphw** [comment]
No, you can extract the (raw) type from the call site in the declaring class.

**Comment by szpak** [comment]
What do you think about the idea to report a feature request (a regression?) in OpenJDK to provide a way to gather that information also in Java 9?

**Comment by raphw** [comment]
I would absolutely recommend you to go for such a request. I do not think that it will be a priority, but you should inform about these things.

**Comment by csoroiu** [comment]
Hi all,
I did some experiments and also i was using a different approach for java 9 at the moment.
In [lambdamatchers](https://github.com/csoroiu/lambdamatchers/tree/methodref/src/main/java/_shaded/net/jodah/typetools) methodref branch, I have a copy of `TypeResolver` which i changed to allow injecting a *lambda method reference resolver*.

And for java 9 I am using the `DumpedLambdaByteCodeMethodRefResolver` which is based on ASM and the system property `jdk.internal.lambda.dumpProxyClasses` which, when is set to a valid path, it is used by LambdaMetafactory to dump the bytecode of the lambda itself.

If you are interested you can take a look at [SmartMethodRefResolver.java](https://github.com/csoroiu/lambdamatchers/blob/methodref/src/main/java/ro/derbederos/hamcrest/internal/SmartMethodRefResolver.java) which is actually a strategy which selects the proper resolver based on the java version.

Those are only experiments on the `methodref` branch, and when stable enough I can add create a pull request for typetools, if you agree.

Anyway, I would go for  a public mechanism to get the hands on the bytecode of an anonymous class at runtime (not intending to instrument it, but inspect it), rather than exposing the internal `ConstantPool`, because the logic based on the `ConstantPool` is pure heuristics and might break at any time. For instance, for a non-anonymous class, the bytecode can be instrumented by a code coverage tool or profiling tool (e.g. when using [retrolambda](https://github.com/orfjackal/retrolambda)) and the `ConstantPool` gets polluted, affecting the heuristics.

An example of a mechanism to get the bytecode of a class could be:
```java
    byte[] getByteCodeOf(Class<?> lambdaClass) throws IOException {
        String name = getRealClassName(lambdaClass);
        int idx = name.lastIndexOf('.');
        final String classFileName = name.substring(idx + 1) + ".class";
        URL url = lambdaClass.getResource(classFileName);
        if (url == null) {
            return null;
        }
        URLConnection urlConnection = url.openConnection();
        int size = urlConnection.getContentLength();
        if (size <= 0) {
            return null;
        } else {
            return readFully(urlConnection.getInputStream(), size);
        }
```

**Comment by szpak** [comment]
@csoroiu ugly and fragile hack, however for me it's better than nothing (I don't know about possible side effects).

Coming back to OpenJDK request I would report it to be available directly, however, I'm not very savvy about bytecode which would be beneficial in a case of extra questions. Maybe one of you could report that?

**Comment by jhalterman** [comment]
@csoroiu Since `ConstantPool` was moved to the `jdk.internal.reflect.ConstantPool` package in Java 9, have you tried resolving it from there? I haven't yet, but that would be the simplest and easiest solution here :)

Regarding the lambdamatchers/ASM approach, it's pretty cool, but I'm guessing that `jdk.internal.lambda.dumpProxyClasses` would be a deal breaker for many users.

Overall, without some [reflect API support](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getGenericSuperclass--) for resolving lambda types args, similar to what we use for resolving other type args, we're probably left with hacky stuff that is specific to various runtimes. It is what it is. In the case of OpenJDK this has meant using `ConstantPool`, which again - hacky - but worked fine.

@szpak Ideally, we should want the JDK to properly support reflection of lambda type arguments. I doubt such a request would be a priority anytime soon, but with so many users and libraries developers interested in this (I hear from a lot of other people about this as well), I'm sure it's worth requesting. Any idea how to proceed - or @raphw?

**Comment by raphw** [comment]
You can always use `sun.misc.Unsafe` which is currently available and exported on Jigsaw to approach this. You would first get an instance which is stored in a private field `theUnsafe` You can then use this class to get hold of the reflective accessors to the new type. This type's methods cannot normally be made accessible as the `jdk.` packages are not exported but using `Unsafe::setField`, it is possible to directly set `AccessibleObject::override` to `true`.

**Comment by csoroiu** [comment]
@jhalterman On the `java.internal.lambda.dumpProxyClasses` setting, this one allowed me to experiment on Java 9, I agree it might be a pain for a production application to run with that setting configured. For my particular case I use it only in unit tests. Mockito, similarly, is being used mostly in unit tests.

@jhalterman, previously I tested using the traditional approach of setting the object accessible but I was getting an error like:
```java
java.lang.reflect.InaccessibleObjectException: Unable to make native jdk.internal.reflect.ConstantPool java.lang.Class.getConstantPool() accessible: module java.base does not "opens java.lang" to unnamed module @6fc6f14e
	at java.base/jdk.internal.reflect.Reflection.throwInaccessibleObjectException(Reflection.java:427)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:201)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:192)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:186)
	at ro.derbederos.hamcrest.internal.J9ConstantPoolMethodRefResolver.<clinit>(J9ConstantPoolMethodRefResolver.java:38)
```
Thanks @raphw. Using `Unsafe::putBoolean` does the trick, as it is bypassing the security checks inside `AccesibleObject`. It is a not so nice hack, but works.

I will prepare a PR for this, after i clean up the code a little bit and I'll be using the same approach for java 8.

**Comment by jhalterman** [comment]
@csoroiu That sounds good, thanks. Continuing with the ConstantPool approach for JDK 9 would at least be the least disruptive.

**Comment by csoroiu** [comment]
The latest changset #fc89497 should contain the support for Java 9. I created #35 PR.

**Comment by jhalterman** [comment]
@szpak I just merged @csoroiu's PR, #35. This adds a dependency on `sun.misc.Unsafe` and uses the technique @raphw [described above](https://github.com/jhalterman/typetools/issues/34#issuecomment-270971763) for getting a reference to the `ConstantPool`. This seems to work in Java 9. Try against master and see how it works for you.

**Comment by szpak** [comment]
Some time ago I "borrowed" that class from PR to use it directly and it worked fine. If there were no changes around the merge it should work fine from master.

**Comment by overfullstack** [comment]
Hi, thanks for this awesome library. But unfortunately, I see this is again broken in Java 11 with the same exception, do you have any plans to add support for Java 11?
