### ISSUE TITLE
Could you possibly provide an example solving this?

### ISSUE THREAD

**Issue by Mrodent** [jhalterman/typetools#39]
This looks extremely clever... but is there any way of getting this to print "javax.swing.Action":

		Bod<Action> bod = new Bod<Action>();
                //Class<?> typeArg = TypeResolver.resolveRawArgument( Bod.class, bod.getClass() );
		Type typeArg = TypeResolver.resolveGenericType( Bod.class, bod.getClass() );
		// just prints the class name, "Bod"
		printOut( String.format( "# typeArg %s", typeArg ));

where Bod is a "nothing" class:

	static class Bod<V> {
		Bod() {
		}
	}

**Comment by jhalterman** [comment]
The only way to recover type information at runtime is, generally, if it's captured in a type declaration. A simple instantiation like `new Bod<Action>()` isn't enough since `Action` is erased at runtime. But if you were to create an anonymous class instead:

```
Bod<Action> bod = new Bod<Action>() {};
```

or a named type declaration:

```
class ActionBod extends Bod<Action>{}
```

Then the `Action` type arg can be recovered from either of those:

```
TypeResolver.resolveRawArgument(Bod.class, bod.getClass());

TypeResolver.resolveRawArgument(Bod.class, ActionBod);
```

**Comment by Mrodent** [comment]
Thanks...
